name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and tag Docker images
        run: |
          docker build  -t udagram-reverseproxy:$GITHUB_SHA -f ./udagram-reverseproxy/Dockerfile ./udagram-reverseproxy
          docker tag udagram-reverseproxy:$GITHUB_SHA hungle14/reverseproxy:latest
          docker push hungle14/reverseproxy:latest
          docker build  -t udagram-frontend:$GITHUB_SHA -f ./udagram-frontend/Dockerfile ./udagram-frontend
          docker tag udagram-frontend:$GITHUB_SHA hungle14/udagram-frontend:latest
          docker push hungle14/udagram-frontend:latest
          docker build  -t udagram-api-feed:$GITHUB_SHA -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
          docker tag udagram-api-feed:$GITHUB_SHA hungle14/udagram-api-feed:latest
          docker push hungle14/udagram-api-feed:latest
          docker build  -t udagram-api-user:$GITHUB_SHA -f ./udagram-api-user/Dockerfile ./udagram-api-user
          docker tag :$GITHUB_SHA hungle14/udagram-api-user:latest
          docker push hungle14/udagram-api-user:latest
